### ISSUE TITLE
Exception raised during pretty printing.

### ISSUE THREAD

**Issue by simendsjo** [fsharp/fsharp#486]
```
Exception raised during pretty printing.
Please report this so it can be fixed.
Trace: System.InvalidCastException: Unable to cast object of type 'Choice1Of2[simendsjo.Yr.HourByHour.Country+T,simendsjo.Yr.HourByHour.AllLetters+CreateError]' to type 'Microsoft.FSharp.Core.FSharpChoice`2[simendsjo.Yr.HourByHour.Country+T,simendsjo.Yr.HourByHour.AllLetters+CreateError]'.
   at Microsoft.FSharp.Compiler.Interactive.Shell.Utilities.AnyToLayoutSpecialization`1.Microsoft-FSharp-Compiler-Interactive-Shell-Utilities-IAnyToLayoutCall-FsiAnyToLayout(FormatOptions options, Object o)
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiValuePrinter.PrintValue(FsiValuePrinterMode printMode, FormatOptions opts, Object x, Type ty)


Exception raised during pretty printing.
Please report this so it can be fixed.
Trace: System.InvalidCastException: Unable to cast object of type 'Choice2Of2[simendsjo.Yr.HourByHour.Country+T,simendsjo.Yr.HourByHour.AllLetters+CreateError]' to type 'Microsoft.FSharp.Core.FSharpChoice`2[simendsjo.Yr.HourByHour.Country+T,simendsjo.Yr.HourByHour.AllLetters+CreateError]'.
   at Microsoft.FSharp.Compiler.Interactive.Shell.Utilities.AnyToLayoutSpecialization`1.Microsoft-FSharp-Compiler-Interactive-Shell-Utilities-IAnyToLayoutCall-FsiAnyToLayout(FormatOptions options, Object o)
   at Microsoft.FSharp.Compiler.Interactive.Shell.FsiValuePrinter.PrintValue(FsiValuePrinterMode printMode, FormatOptions opts, Object x, Type ty)
```

Using VS 2013 with Visual F# 3.1.2, fsi 12.0.30815.0 and .NET 4.5.1 (I'm actually marking code in an `.fsx` file in the project folder and choosing run in interactive. No idea if the interactive shell in VS uses that .NET version). I get the same error running in 32-bit and 64-bit mode in the FSI.

I have just started looking at F#, so please give some details if you need more information to locate this error.

**Comment by latkin** [comment]
Please open this at http://github.com/microsoft/visualfsharp, that is where core compiler/runtime issues are tracked and addressed.

If you could provide a minimal self-contained repro with code that would be very helpful.

**Comment by dsyme** [comment]
Closing as this belongs at http://github.com/microsoft/visualfsharp (this repo is for cross-platform issues)
