### ISSUE TITLE
Seq.Length handles data holes poorly

### ISSUE THREAD

**Issue by drcrook1** [fsharp/fsharp#569]
Please provide a succinct description of the issue.

#### Repro steps

Provide the steps required to reproduce the problem

1. Download sample data: https://opendata.miamidade.gov/311/311-Service-Requests-Miami-Dade-County/dj6j-qg5t

2. Install fslab nuget package (or fsharp.data)

3.  Create new type with CsvProvider

4.  Load data with type provider

5.  Attempt to get length of the sequence

type m311C = CsvProvider<"C:\\data\\Miami_311.csv">
let m311 = m311C.Load("C:\\data\\Miami_311.csv")

m311.Rows |> Seq.length

#### Expected behavior

returns an integer amount of the data set.  Should be ~810,000 or so.

#### Actual behavior

Crash:
System.Exception: Couldn't parse row 6515 according to schema: Ticket Closed Date / Time is missing
>    at FSharp.Data.Runtime.CsvHelpers.parseIntoTypedRows@203-6.Invoke(String message) in C:\Git\FSharp.Data\src\Csv\CsvRuntime.fs:line 203
   at FSharp.Data.Runtime.CsvHelpers.parseIntoTypedRows@176.GenerateNext(IEnumerable`1& next) in C:\Git\FSharp.Data\src\Csv\CsvRuntime.fs:line 203
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl()
   at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.oneStepTo@1403[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i)
   at Microsoft.FSharp.Collections.SeqModule.f@4728-2[T](IEnumerable`1 source, List`1 prefix, FSharpRef`1 enumeratorR, Int32 i, Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.result@1419.Invoke(Int32 i)
   at Microsoft.FSharp.Collections.IEnumerator.unfold@236.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.Length[T](IEnumerable`1 source)
   at <StartupCode$FSI_0009>.$FSI_0009.main@() in C:\projects\deleteme\ASPNet5Test\ConsoleApplication1\MyWebCharting\Script.fsx:line 14
Stopped due to error. 

#### Known workarounds

Fill data holes with guessed data.

#### Related information 

Provide any related information 

* Win 10
* VS 2015 Update 3
* .NET Runtime, CoreCLR or Mono Version
* Editing Tools (e.g. Visual Studio Version)
* Links to F# RFCs or entries on http://fslang.uservoice.com
* Links to performance testing scripts
* Prepping talks for user groups, so severity not so bad, but does provide barriers to adoption.

**Comment by drcrook1** [comment]
Should use this: type m311C = CsvProvider<"C:\\data\\Miami_311.csv",
                            AssumeMissingValues=true> 

Would be nice if

**Comment by drcrook1** [comment]
This issue actually lies in FSharp.Data.  Closing and moving to FSharp.Data.
