### ISSUE TITLE
Marshal.OffsetOf is throwing an System.ArgumentException when called from F#

### ISSUE THREAD

**Issue by tencek** [fsharp/fsharp#866]
I'm using `InteropServices` to call unmanaged C++ code from F#.
Al seems to be working correctly but I'm getting an unexpected exception when using `Marshal.OffsetOf` method.

#### Repro steps

In the F# interactive concole, try this:

```F#
open System.Runtime.InteropServices

[<StructLayout(LayoutKind.Sequential)>]
type XYZ = {
    abc:int64
}

Marshal.OffsetOf<XYZ>("abc") |> printfn "Offset = %d"
```

#### Expected behavior

`Offset = 0` written into the fsi console

#### Actual behavior

```
System.ArgumentException: Field passed in is not a marshaled member of the type 'FSI_0059+XYZ'.
Parameter name: fieldName
   at System.Runtime.InteropServices.Marshal.OffsetOf(Type t, String fieldName)
   at System.Runtime.InteropServices.Marshal.OffsetOf[T](String fieldName)
   at FSI_0059.printOffset() in myscriptfile.fsx:line 33
```
the exception comes from the `mscorlib.dll!System.Reflection.Emit.TypeBuilder.InvokeMember`, the whole callstack is
```
FSI-ASSEMBLY.dll!<StartupCode$FSI_0005>.$FSI_0005.main@() Line 38
	at myscript.fsx(38)
[Native to Managed Transition]
[Managed to Native Transition]
mscorlib.dll!System.Reflection.Emit.TypeBuilder.InvokeMember(string name, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, object target, object[] args, System.Reflection.ParameterModifier[] modifiers, System.Globalization.CultureInfo culture, string[] namedParameters) Line 1082
	at f:\dd\ndp\clr\src\BCL\system\reflection\emit\typebuilder.cs(1082)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.AbstractIL.ILRuntimeWriter.execEntryPtFun@2089.Invoke(System.Tuple<System.Reflection.Emit.TypeBuilder, string> tupledArg, Microsoft.FSharp.Core.Unit unitVar2)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.clo@1088-283.Invoke(Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Core.Unit, Microsoft.FSharp.Core.FSharpOption<System.Exception>> exec)
FSharp.Core.dll!Microsoft.FSharp.Primitives.Basics.List.iter<System.__Canon>(Microsoft.FSharp.Core.FSharpFunc<System.__Canon, Microsoft.FSharp.Core.Unit> f, Microsoft.FSharp.Collections.FSharpList<System.__Canon> x)
FSharp.Core.dll!Microsoft.FSharp.Collections.ListModule.Iterate<Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Core.Unit, Microsoft.FSharp.Core.FSharpOption<System.Exception>>>(Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Core.Unit, Microsoft.FSharp.Core.FSharpOption<System.Exception>>, Microsoft.FSharp.Core.Unit> action, Microsoft.FSharp.Collections.FSharpList<Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Core.Unit, Microsoft.FSharp.Core.FSharpOption<System.Exception>>> list)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompiler.ProcessInputs(Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CompilationThreadToken ctok, Microsoft.FSharp.Compiler.ErrorLogger.ErrorLogger errorLogger, Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState istate, Microsoft.FSharp.Collections.FSharpList<Microsoft.FSharp.Compiler.Ast.ParsedInput> inputs, bool showTypes, bool isIncrementalFragment, bool isInteractiveItExpr, Microsoft.FSharp.Collections.FSharpList<Microsoft.FSharp.Compiler.Ast.Ident> prefixPath)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompiler.EvalParsedDefinitions(Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CompilationThreadToken ctok, Microsoft.FSharp.Compiler.ErrorLogger.ErrorLogger errorLogger, Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState istate, bool showTypes, bool isInteractiveItExpr, Microsoft.FSharp.Collections.FSharpList<Microsoft.FSharp.Compiler.Ast.SynModuleDecl> defs)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompiler.EvalParsedExpression(Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CompilationThreadToken ctok, Microsoft.FSharp.Compiler.ErrorLogger.ErrorLogger errorLogger, Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState istate, Microsoft.FSharp.Compiler.Ast.SynExpr expr)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.clo@1898-291.Invoke(Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState istate)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.InteractiveCatch<Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState>(Microsoft.FSharp.Compiler.ErrorLogger.ErrorLogger errorLogger, Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState, System.Tuple<Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState, Microsoft.FSharp.Compiler.Interactive.Shell.FsiInteractionStepStatus>> f, Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState istate)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.ExecInteraction(Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CompilationThreadToken ctok, Microsoft.FSharp.Compiler.CompileOps.TcConfig tcConfig, Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState istate, Microsoft.FSharp.Compiler.Ast.ParsedFsiInteraction action, Microsoft.FSharp.Compiler.ErrorLogger.ErrorLogger errorLogger)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.execParsedInteractions(Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CompilationThreadToken ctok, Microsoft.FSharp.Compiler.CompileOps.TcConfig tcConfig, Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState istate, Microsoft.FSharp.Core.FSharpOption<Microsoft.FSharp.Compiler.Ast.ParsedFsiInteraction> action, Microsoft.FSharp.Compiler.ErrorLogger.ErrorLogger errorLogger, Microsoft.FSharp.Core.FSharpOption<Microsoft.FSharp.Compiler.Interactive.Shell.FsiInteractionStepStatus> lastResult)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.clo@2077-294.Invoke(Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CompilationThreadToken ctok, Microsoft.FSharp.Compiler.CompileOps.TcConfig tcConfig, Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState istate)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.FsiInteractionProcessor.mainThreadProcessAction<Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CompilationThreadToken, Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState>(Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CompilationThreadToken ctok, Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Compiler.AbstractIL.Internal.Library.CompilationThreadToken, Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Compiler.CompileOps.TcConfig, Microsoft.FSharp.Core.FSharpFunc<Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState, System.Tuple<Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState, Microsoft.FSharp.Compiler.Interactive.Shell.FsiInteractionStepStatus>>>> action, Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState istate)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.res@2140-18.Invoke(Microsoft.FSharp.Compiler.ErrorLogger.ErrorLogger errorLogger, System.Tuple<Microsoft.FSharp.Core.FSharpOption<Microsoft.FSharp.Compiler.Ast.ParsedFsiInteraction>, Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState> tupledArg)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.clo@1830-289<Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState>.Invoke(Microsoft.FSharp.Core.Unit unitVar0)
fsi.exe!Sample.Microsoft.FSharp.Compiler.Interactive.Main.Microsoft-FSharp-Compiler-Interactive-Shell-Settings-IEventLoop-Invoke@104<System.Tuple<Microsoft.FSharp.Compiler.Interactive.Shell.FsiDynamicCompilerState, Microsoft.FSharp.Compiler.Interactive.Shell.FsiInteractionStepStatus>>.Invoke()
System.Windows.Forms.dll!System.Windows.Forms.Control.InvokeMarshaledCallbackDo(System.Windows.Forms.Control.ThreadMethodEntry tme) Line 7442
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Control.cs(7442)
System.Windows.Forms.dll!System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(object obj) Line 7402
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Control.cs(7402)
mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 954
	at f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs(954)
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 902
	at f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs(902)
mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 891
	at f:\dd\ndp\clr\src\BCL\system\threading\executioncontext.cs(891)
System.Windows.Forms.dll!System.Windows.Forms.Control.InvokeMarshaledCallback(System.Windows.Forms.Control.ThreadMethodEntry tme) Line 7387
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Control.cs(7387)
System.Windows.Forms.dll!System.Windows.Forms.Control.InvokeMarshaledCallbacks() Line 7471
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Control.cs(7471)
System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m) Line 14261
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Control.cs(14261)
System.Windows.Forms.dll!System.Windows.Forms.ScrollableControl.WndProc(ref System.Windows.Forms.Message m) Line 1493
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\ScrollableControl.cs(1493)
System.Windows.Forms.dll!System.Windows.Forms.Form.WndProc(ref System.Windows.Forms.Message m) Line 7634
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Form.cs(7634)
System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m) Line 14464
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Control.cs(14464)
System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m) Line 14519
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Control.cs(14519)
System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.Callback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam) Line 650
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\NativeWindow.cs(650)
[Native to Managed Transition]
[Managed to Native Transition]
System.Windows.Forms.dll!System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(System.IntPtr dwComponentID, int reason, int pvLoopData) Line 2079
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Application.cs(2079)
System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(int reason, System.Windows.Forms.ApplicationContext context) Line 3424
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Application.cs(3424)
System.Windows.Forms.dll!System.Windows.Forms.Application.ThreadContext.RunMessageLoop(int reason, System.Windows.Forms.ApplicationContext context) Line 3306
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Application.cs(3306)
System.Windows.Forms.dll!System.Windows.Forms.Application.Run() Line 1484
	at f:\dd\ndp\fx\src\winforms\Managed\System\WinForms\Application.cs(1484)
fsi.exe!Sample.Microsoft.FSharp.Compiler.Interactive.Main.WinFormsEventLoop.Microsoft.FSharp.Compiler.Interactive.Shell.Settings.IEventLoop.Microsoft-FSharp-Compiler-Interactive-Shell-Settings-IEventLoop-Run()
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.runLoop@2382(Microsoft.FSharp.Compiler.Interactive.Shell.FsiConsoleOutput fsiConsoleOutput, Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSessionHostConfig fsi, Microsoft.FSharp.Core.Unit unitVar0)
FSharp.Compiler.Private.dll!Microsoft.FSharp.Compiler.Interactive.Shell.FsiEvaluationSession.Run()
fsi.exe!Sample.Microsoft.FSharp.Compiler.Interactive.Main.evaluateSession(string[] argv)
fsi.exe!Sample.Microsoft.FSharp.Compiler.Interactive.Main.MainMain(string[] argv)
[Native to Managed Transition]
[Managed to Native Transition]
mscorlib.dll!System.AppDomain.ExecuteAssemblyByName(System.Reflection.AssemblyName assemblyName, string[] args) Line 2095
	at f:\dd\ndp\clr\src\BCL\system\appdomain.cs(2095)
[AppDomain (fsi.exe, #1) -> AppDomain (FSI_Domain, #2)]
fsi.exe!Sample.Microsoft.FSharp.Compiler.Interactive.Main.MainMain(string[] argv)
```

#### Known workarounds

The same code written in C# works perfectly fine:
``` C#
using System.Runtime.InteropServices;

[StructLayout(LayoutKind.Sequential)]
struct XYZ
{
    Int64 abc;
}

Marshal.OffsetOf(typeof(XYZ), "abc")
[0]
```

**Comment by zpodlovics** [comment]
Your first example is an F# record (class type) and not a struct, also the layout attribute will be ignored here right now (https://github.com/Microsoft/visualfsharp/issues/5215). Also F# implements read-only fields using a private backing field + getter. Unfortunately it's not yet possible to create proper private field in F# (https://github.com/Microsoft/visualfsharp/issues/5503)

With the first example:

```fsharp
typeof<XYZ>

typeof<XYZ>;;
val it : System.Type =
  FSI_0015+XYZ
    {Assembly = FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null;
     AssemblyQualifiedName = "FSI_0015+XYZ, FSI-ASSEMBLY, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null";
     Attributes = AutoLayout, AnsiClass, Class, NestedPublic, SequentialLayout, Sealed, Serializable;
     BaseType = System.Object;
     ContainsGenericParameters = false;
     CustomAttributes = seq
                          [[Microsoft.FSharp.Core.CompilationMappingAttribute((SourceConstructFlags)RecordType)]];
     DeclaredConstructors = [|Void .ctor(Int64)|];
     DeclaredEvents = [||];
     DeclaredFields = [|System.Int64 abc@|];
```

As you see, there is a DeclaredField called ```abc@```.

If you use the proper field name, you'll get the offset:

```fsharp
Marshal.OffsetOf<XYZ>("abc@") |> printfn "Offset = %d"
```

The rough equivalent should like this (you can always compare the generated IL here:  https://sharplab.io/) :

```fsharp
open System.Runtime.InteropServices

[<NoEquality;NoComparison>]
[<Struct; StructLayout(LayoutKind.Sequential)>]
type XYZ = 
   val mutable private abc: int64

Marshal.OffsetOf<XYZ>("abc") |> printfn "Offset = %d"
```

**Comment by dsyme** [comment]
Closing per answer above
